-- Supabase SQL - Estrutura de NF (nfs, nf_itens, import_logs)
-- Pode ser executado no SQL Editor do Supabase.
-- Seguro para rodar mais de uma vez (idempotente na maior parte).

begin;

-- 1) Funcao padrao para atualizar coluna updated_at
create or replace function public.set_updated_at()
returns trigger
language plpgsql
as $$
begin
  new.updated_at = now();
  return new;
end;
$$;

-- 2) Tabela principal de notas fiscais
create table if not exists public.nfs (
  id bigint generated by default as identity primary key,
  numero_nf text not null,
  serie text not null default '1',
  pedido text not null default '-',
  cliente text not null default 'Cliente nao informado',
  transportadora text not null default 'Nao informada',
  artigo text not null default '-',
  quantidade_itens numeric(14,3) not null default 0,
  metros numeric(14,3) not null default 0,
  peso_bruto numeric(14,3) not null default 0,
  valor_total numeric(14,2) not null default 0,
  data_emissao date null,
  status text not null default 'pendente',
  origem_xml text null,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint nfs_status_check check (status in ('pendente', 'faturada', 'expedida', 'entregue'))
);

-- 2.1) Se a tabela ja existir com colunas faltando, adiciona sem quebrar
alter table public.nfs add column if not exists numero_nf text;
alter table public.nfs add column if not exists serie text;
alter table public.nfs add column if not exists pedido text;
alter table public.nfs add column if not exists cliente text;
alter table public.nfs add column if not exists transportadora text;
alter table public.nfs add column if not exists artigo text;
alter table public.nfs add column if not exists quantidade_itens numeric(14,3) default 0;
alter table public.nfs add column if not exists metros numeric(14,3) default 0;
alter table public.nfs add column if not exists peso_bruto numeric(14,3) default 0;
alter table public.nfs add column if not exists valor_total numeric(14,2) default 0;
alter table public.nfs add column if not exists data_emissao date;
alter table public.nfs add column if not exists status text default 'pendente';
alter table public.nfs add column if not exists origem_xml text;
alter table public.nfs add column if not exists created_at timestamptz default now();
alter table public.nfs add column if not exists updated_at timestamptz default now();

-- 2.1.1) Compatibilidade com schemas legados (criado_em/atualizado_em)
do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'nfs' and column_name = 'criado_em'
  ) then
    update public.nfs
    set created_at = coalesce(created_at, criado_em)
    where created_at is null;
  end if;

  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'nfs' and column_name = 'atualizado_em'
  ) then
    update public.nfs
    set updated_at = coalesce(updated_at, atualizado_em)
    where updated_at is null;
  end if;
end
$$;

-- 2.2) Normaliza nulos apos alter table
update public.nfs
set
  serie = coalesce(nullif(trim(serie), ''), '1'),
  pedido = coalesce(nullif(trim(pedido), ''), '-'),
  cliente = coalesce(nullif(trim(cliente), ''), 'Cliente nao informado'),
  transportadora = coalesce(nullif(trim(transportadora), ''), 'Nao informada'),
  artigo = coalesce(nullif(trim(artigo), ''), '-'),
  quantidade_itens = coalesce(quantidade_itens, 0),
  metros = coalesce(metros, 0),
  peso_bruto = coalesce(peso_bruto, 0),
  valor_total = coalesce(valor_total, 0),
  status = coalesce(nullif(trim(status), ''), 'pendente'),
  created_at = coalesce(created_at, now()),
  updated_at = coalesce(updated_at, now())
where
  serie is null
  or pedido is null
  or cliente is null
  or transportadora is null
  or artigo is null
  or quantidade_itens is null
  or metros is null
  or peso_bruto is null
  or valor_total is null
  or status is null
  or created_at is null
  or updated_at is null;

-- 2.3) Remove NFs duplicadas por numero_nf, mantendo o registro mais novo (maior id)
with ranked as (
  select
    id,
    numero_nf,
    row_number() over (partition by numero_nf order by id desc) as rn
  from public.nfs
  where numero_nf is not null and trim(numero_nf) <> ''
)
delete from public.nfs n
using ranked r
where n.id = r.id
  and r.rn > 1;

-- 2.4) Constraint de unicidade por numero_nf (fundamental para upsert/importador)
create unique index if not exists nfs_numero_nf_uidx on public.nfs (numero_nf);

-- 2.5) Indices de consulta
create index if not exists nfs_status_idx on public.nfs (status);
create index if not exists nfs_data_emissao_idx on public.nfs (data_emissao desc);
create index if not exists nfs_transportadora_idx on public.nfs (transportadora);

-- 2.6) Trigger de updated_at

drop trigger if exists trg_nfs_set_updated_at on public.nfs;
create trigger trg_nfs_set_updated_at
before update on public.nfs
for each row
execute function public.set_updated_at();

-- 3) Itens da NF
create table if not exists public.nf_itens (
  id bigint generated by default as identity primary key,
  nf_id bigint not null references public.nfs(id) on delete cascade,
  codigo text null,
  descricao text null,
  unidade text null,
  quantidade numeric(14,3) not null default 0,
  valor_unitario numeric(14,4) not null default 0,
  valor_total numeric(14,2) not null default 0,
  created_at timestamptz not null default now()
);

alter table public.nf_itens add column if not exists created_at timestamptz default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'nf_itens' and column_name = 'criado_em'
  ) then
    update public.nf_itens
    set created_at = coalesce(created_at, criado_em)
    where created_at is null;
  end if;
end
$$;

create index if not exists nf_itens_nf_id_idx on public.nf_itens (nf_id);

-- 4) Logs de importacao
create table if not exists public.import_logs (
  id bigint generated by default as identity primary key,
  arquivo text not null,
  numero_nf text null,
  chave_acesso text null,
  status text not null,
  mensagem text null,
  created_at timestamptz not null default now()
);

alter table public.import_logs add column if not exists created_at timestamptz default now();

do $$
begin
  if exists (
    select 1 from information_schema.columns
    where table_schema = 'public' and table_name = 'import_logs' and column_name = 'criado_em'
  ) then
    update public.import_logs
    set created_at = coalesce(created_at, criado_em)
    where created_at is null;
  end if;
end
$$;

create index if not exists import_logs_created_at_idx on public.import_logs (created_at desc);
create index if not exists import_logs_numero_nf_idx on public.import_logs (numero_nf);

-- 5) RLS + policies basicas
alter table public.nfs enable row level security;
alter table public.nf_itens enable row level security;
alter table public.import_logs enable row level security;

-- Leitura para usuarios autenticados
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'nfs' and policyname = 'nfs_select_authenticated'
  ) then
    create policy "nfs_select_authenticated"
    on public.nfs
    for select
    to authenticated
    using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'nf_itens' and policyname = 'nf_itens_select_authenticated'
  ) then
    create policy "nf_itens_select_authenticated"
    on public.nf_itens
    for select
    to authenticated
    using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'import_logs' and policyname = 'import_logs_select_authenticated'
  ) then
    create policy "import_logs_select_authenticated"
    on public.import_logs
    for select
    to authenticated
    using (true);
  end if;
end
$$;

-- Escrita para usuarios autenticados (app web)
do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'nfs' and policyname = 'nfs_insert_authenticated'
  ) then
    create policy "nfs_insert_authenticated"
    on public.nfs
    for insert
    to authenticated
    with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'nfs' and policyname = 'nfs_update_authenticated'
  ) then
    create policy "nfs_update_authenticated"
    on public.nfs
    for update
    to authenticated
    using (true)
    with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'nf_itens' and policyname = 'nf_itens_insert_authenticated'
  ) then
    create policy "nf_itens_insert_authenticated"
    on public.nf_itens
    for insert
    to authenticated
    with check (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'nf_itens' and policyname = 'nf_itens_delete_authenticated'
  ) then
    create policy "nf_itens_delete_authenticated"
    on public.nf_itens
    for delete
    to authenticated
    using (true);
  end if;
end
$$;

do $$
begin
  if not exists (
    select 1 from pg_policies
    where schemaname = 'public' and tablename = 'import_logs' and policyname = 'import_logs_insert_authenticated'
  ) then
    create policy "import_logs_insert_authenticated"
    on public.import_logs
    for insert
    to authenticated
    with check (true);
  end if;
end
$$;

commit;
